// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalPortfolio;

#nullable disable

namespace PersonalPortfolio.Migrations
{
    [DbContext(typeof(PortfolioContext))]
    [Migration("20240627225006_ModificationInEnumAndID")]
    partial class ModificationInEnumAndID
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("PersonalPortfolio.Experience", b =>
                {
                    b.Property<string>("Title")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(70)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(230)
                        .HasColumnType("TEXT");

                    b.HasKey("Title");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("PersonalPortfolio.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExperienceTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceTitle");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("PersonalPortfolio.Skill", b =>
                {
                    b.HasOne("PersonalPortfolio.Experience", null)
                        .WithMany("Skills")
                        .HasForeignKey("ExperienceTitle");
                });

            modelBuilder.Entity("PersonalPortfolio.Experience", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
